name: quickdialogs
version: 1.4.3
description: Quick HTML dialogs w/o having to write markup
author: Adrián Avila <adrian.avila.mtz@gmail.com>
homepage: https://github.com/adrianlmm/quickdialogs
environment:
  sdk: '>=1.20.1 <3.0.0'
dependencies:
  browser: any